### PR TITLE
fix(components/home): update automatic org descriptions

### LINKED ISSUE #132: Update automatic org descriptions
**Describe the bug**
The automatically generated org descriptions showcased in `pages/[org]/index.tsx` are messed up when the org only has one aspect. For example, this is [AAR's org description](https://tutorbook.app/aar):
> Advanced Authentic Research is using Tutorbook to manage it's mentoring programs. You can use Tutorbook to sign-up as a  or mentor or search Advanced Authentic Research's existing  and mentors.

### PR DESCRIPTION
**Pull request by evanyang1**
Fixes #132.

### CODE REVIEW

File: components/home/index.tsx [hunk 1]
```diff
@@ -19,17 +19,23 @@ export default function Home({ org }: HomeProps): JSX.Element {
...
     const as = org ? org.aspects : ['tutoring', 'mentoring'];
+    console.log('AS: ', as);
     let person = '';
     let people = '';
     if (as.includes('tutoring')) {
       person += 'tutor';
       people += 'tutors';
     }
-    if (as.includes('mentoring')) {
+    console.log(as.length);
```
Comment (nicholaschiang) [inline components/home/index.tsx:29]: Let's remove all these `console.log` statements.

**Review by nicholaschiang — CHANGES_REQUESTED** [review]
Just drop the `console.log` calls. Otherwise, this LGTM!

**Review by nicholaschiang — APPROVED** [review]
Awesome, thanks! You've officially made your first contribution haha.
